name: macos_calculator
version: 1.0.0+1
publish_to: none
description: A cross platform calculator written in flutter that resembles macos calculator.
environment: 
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  bitsdojo_window: ^0.1.5
  flutter_acrylic: ^1.0.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

